# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-30 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180815_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='start_time',
        ),
    ]
