# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-07 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Male'), (2, 'Female')], default=0),
        ),
    ]
