# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20181007_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verify_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
